services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: >
      start-dev
      --spi-theme-static-max-age=-1
      --spi-theme-cache-themes=false
      --spi-theme-cache-templates=false
    ports:
      - "8443:8443"
    volumes:
      - ./certs/keycloak.p12:/etc/x509/https/keycloak.p12:ro
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database configuration
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      # HTTPS configuration
      KC_HTTPS_KEY_STORE_FILE: /etc/x509/https/keycloak.p12
      KC_HTTPS_KEY_STORE_PASSWORD: pass
      KC_HTTPS_KEY_STORE_TYPE: PKCS12
      KC_HTTPS_PORT: 8443

      # Relax hostname checks for development
      KC_HOSTNAME_URL: https://localhost:8443
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: